fix: add ajv-formats dependency to package.json (#8)
was getting
```

> quacker-community-packs@1.0.0 validate
> node scripts/validate.js

node:internal/modules/cjs/loader:1478
  throw err;
  ^

Error: Cannot find module 'ajv-formats'
Require stack:
- /Users/robert/workspace/quacker-community-packs/scripts/validate.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1475:15)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1048:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1072:10)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1093:12)
    at Module._load (node:internal/modules/cjs/loader:1261:25)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1575:12)
    at require (node:internal/modules/helpers:191:16)
    at Object.<anonymous> (/Users/robert/workspace/quacker-community-packs/scripts/validate.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1829:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/robert/workspace/quacker-community-packs/scripts/validate.js'
  ]
}

Node.js v25.9.0
```

when trying to validate the package